# Generated by Django 5.2.7 on 2025-10-22 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringProperties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.IntegerField()),
                ('is_palindrome', models.BooleanField(default=False)),
                ('word_count', models.IntegerField()),
                ('string_hash', models.CharField(max_length=500)),
                ('character_frequency_map', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.CharField(max_length=500)),
                ('value', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Analyzer.stringproperties')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
