# Generated by Django 5.2.7 on 2025-10-22 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='properties',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='string', to='Analyzer.stringproperties'),
        ),
        migrations.AlterField(
            model_name='string',
            name='id',
            field=models.CharField(max_length=500, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='string',
            name='value',
            field=models.TextField(),
        ),
    ]
